name: HidenCloud Auto Renew

on:
  schedule:
    - cron: '0 3 * * *'  # 每天 UTC 18:00，可按需调整
  workflow_dispatch:

jobs:
  renew:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install playwright
        playwright install chromium

    - name: Run auto renewal
      env:
        REMEMBER_WEB_COOKIE: ${{ secrets.REMEMBER_WEB_COOKIE }}
        HIDEN_EMAIL: ${{ secrets.HIDEN_EMAIL }}
        HIDEN_PASSWORD: ${{ secrets.HIDEN_PASSWORD }}
        HIDEN_SERVICE_URL: ${{ secrets.HIDEN_SERVICE_URL }}
      run: python main.py

    - name: Commit README file
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        if git diff --cached --quiet; then
          echo "README文件无变化，无需提交"
        else
          git commit -m "📝 更新运行状态: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin HEAD:main
        fi
